### ISSUE TITLE
Add-on name and description no longer visible

### ISSUE THREAD

**Issue by Poorchop** [jtojnar/google-image#3]
As of Firefox 55.0.3 (Windows 8.1, 64-bit Firefox), the name of the add-on just appears as "addon_name 0.0.6" and the description is simply "addon_description." I think that this has to do with Mozilla's planned migration to WebExtensions since the add-on is now marked as legacy but all of my other add-ons still appear normally in the list aside from the legacy warning.

![untitled](https://user-images.githubusercontent.com/5256208/29744753-7e85c9c2-8a79-11e7-8511-a7944fc9cf46.png)

**Comment by jtojnar** [comment]
Thanks for letting me know. Unfortunately, I stopped the development of this add-on.

I do have a web-ext version ready since September 2016 but I have put off its release due to [missing API](https://bugzilla.mozilla.org/show_bug.cgi?id=1238314), wanting to keep full feature parity with the original add-on. While I was waiting, new WebExtensions with the same limitations have sprung up. Since my extension is essentially the same as the new ones and the missing feature will appear in Firefox 57, I have decided to deprecate my extension in favour of one of them, in particular [Image reverse search with Google](https://addons.mozilla.org/en-US/firefox/addon/image-reverse-search/).
